---
- name: Hello Ansible - quick start
  hosts: localhost
  user: vagrant

  tasks:
    #- name: Hello server
    #  shell: date >> now.txt

    - name: vim
      become: yes
      shell: aptitude install -y vim-gnome

    - name: clone dotfiles
      git: repo=https://github.com/naofumi-fujii/dotfiles.git dest=/home/vagrant/dotfiles
