---
- name: Vagrant Ansible Sample
  hosts: all
  user: vagrant
  vars:
    nodejs_npm_global_packages:
      - name: jslint
      - name: node-sass
      - name: phantomjs
      - name: purify-css
      - name: strip-css-comments-cli
      - name: n

  tasks:
    - name: update node to latest version
      become: yes
      shell: |
        n latest
        npm update -g npm

  roles:
    - role: geerlingguy.nodejs
      become: yes
