---
- name: Vagrant Ansible Sample
  hosts: all
  user: vagrant

  tasks:
    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        - build-essential
        - tmux
        - vim-gnome
        - zsh
        - libmysqlclient-dev
        - libmagickwand-dev

  roles:
    - role: spitfast.rbenv
    - role: geerlingguy.mysql
      become: yes
