---
- name: local-slackbot-env
  hosts: all
  user: vagrant
  vars:
    nodejs_npm_global_packages:
      - name: n

  tasks:
    - name: update node to latest version
      become: yes
      shell: |
        n latest
        npm update -g npm
        
    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        
    - name: git clone botkit
      git: repo=https://github.com/howdyai/botkit.git dest=/home/vagrant/botkit

  roles:
    - role: geerlingguy.nodejs
      become: yes
