---
- name: Hello Ansible - quick start
  hosts: localhost
  user: vagrant

  tasks:
    #- name: Hello server
    #  shell: date >> now.txt

    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - build-essential
        - zsh

    - name: vim
      become: yes
      shell: aptitude install -y vim-gnome

    - name: clone dotfiles
      git: repo=https://github.com/naofumi-fujii/dotfiles.git dest=/home/vagrant/dotfiles

    - name: install dein.vim
      shell: |
        curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
        sh ./installer.sh .

    - name: .vimrc
      get_url:
        url=https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.vimrc dest=/home/vagrant/.vimrc

    - name: .zshrc
      get_url:
        url=https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.zshrc dest=/home/vagrant/.zshrc

    - name: change vimrc path to vagrant
      shell: |
        sed -i -e "s/\/Users\/naofumi.fujii\//\/home\/vagrant\//g" .vimrc

    - name: .tmux.conf
      get_url:
        url=https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.tmux.conf dest=/home/vagrant/.tmux.conf

    - name: git alias
      shell: |
        git config --global alias.st status

    - name: Be sure shell is zsh
      command: grep vagrant /etc/passwd
      register: resultsh

    - name: Change shell to zsh
      command: chsh -s /bin/zsh vagrant
      when: resultsh.stdout.find('/bin/zsh') == -1
