---
- name: Vagrant Ansible Sample
  hosts: all
  user: vagrant
  vars:
    rbenv_ruby_version: 2.3.1
    rbenv_gems:
      - bundler
      - rubocop
    nodejs_npm_global_packages:
      - name: jslint
      - name: node-sass
      - name: phantomjs
      - name: purify-css
      - name: strip-css-comments-cli
      - name: n

  tasks:
    - name: set git alias
      shell: git config --global alias.st status

    - name: update node
      become: yes
      shell: |
        n latest
        npm update -g npm

    - name: install dein.vim
      shell: |
        curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > /home/vagrant/installer.sh
        sh /home/vagrant/installer.sh /home/vagrant

    - name: download .vimrc
      get_url:
        url: https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.vimrc
        dest: /home/vagrant/.vimrc

    - name: download .zlogin
      get_url:
        url: https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.zlogin
        dest: /home/vagrant/.zlogin

    - name: download .tmux.conf
      get_url:
        url: https://raw.githubusercontent.com/naofumi-fujii/dotfiles/master/.tmux.conf
        dest: /home/vagrant/.tmux.conf

    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        - nkf
        - build-essential
        - vim-gnome
        - fonts-ipafont
        - libmysqlclient-dev
        - libmagickwand-dev

  roles:
    - role: vaulttec.zsh
    - role: joshualund.golang
      become: yes
    - role: spitfast.rbenv
    - role: geerlingguy.nodejs
      become: yes
    - role: geerlingguy.mysql
      become: yes
