---
- name: Hello Ansible - quick start
  hosts: all
  user: vagrant

  tasks:
    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        - build-essential
        - tmux
        - vim-gnome
        - zsh

  roles:
    - role: zzet.rbenv
