---
- name: Vagrant Ansible Sample
  hosts: all
  user: vagrant
  vars:
    nodejs_npm_global_packages:
      - name: jslint
      - name: node-sass
      - name: phantomjs

  tasks:
    - name: install packages
      become: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - git
        - build-essential
        - phantomjs
        - tmux
        - vim-gnome
        - zsh
        - fonts-ipafont
        - libmysqlclient-dev
        - libmagickwand-dev

  roles:
    - role: spitfast.rbenv
    - role: geerlingguy.nodejs
    - role: geerlingguy.mysql
      become: yes
